# Generated by Django 4.0.2 on 2022-02-14 14:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import plataforma.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_album', models.CharField(max_length=30)),
                ('carregado_em', models.DateField(default=datetime.datetime(2022, 2, 14, 14, 11, 48, 661965, tzinfo=utc))),
                ('logo_album', models.FileField(upload_to=plataforma.models.user_directory_path)),
                ('genero_album', models.CharField(max_length=30)),
                ('artista_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albuns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_musica', models.CharField(max_length=40)),
                ('arquivo_musica', models.FileField(upload_to=plataforma.models.user_directory_path_song)),
                ('album_musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicas', to='plataforma.album')),
            ],
        ),
    ]
